//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCareBd1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int billId { get; set; }
        public Nullable<System.DateTime> billDate { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> serviceId { get; set; }
        public Nullable<int> employeeId { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual employees employees { get; set; }
        public virtual t_services t_services { get; set; }
        public virtual users users { get; set; }
    }
}
