//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCareBd1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pets
    {
        public int petId { get; set; }
        public string petName { get; set; }
        public string petType { get; set; }
        public string petColor { get; set; }
        public string petRace { get; set; }
        public Nullable<int> customerOwnerId { get; set; }
    
        public virtual customers customers { get; set; }
    }
}
