//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetCareBd1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_services()
        {
            this.bill = new HashSet<bill>();
        }
    
        public int serviceId { get; set; }
        public string serviceName { get; set; }
        public string serviceDescription { get; set; }
        public Nullable<decimal> servicePrice { get; set; }
        public Nullable<System.TimeSpan> serviceduration { get; set; }
        public Nullable<int> serviceTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bill> bill { get; set; }
        public virtual serviceType serviceType { get; set; }
    }
}
